name: Testjps
favicon: null
layout_spectrum: 0.39923
typography_spectrum: 0.55538
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161611'
    - '#cdd3f0'
    - '#695859'
    - '#a68175'
    - '#cba34d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
