name: Testjps
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18847
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050a10'
    - '#cae8f3'
    - '#1f2d36'
    - '#807876'
    - '#b9a896'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
