name: Testjps
favicon: null
layout_spectrum: 0.0023
typography_spectrum: 0.9823233284987509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000509'
    - '#cae6f2'
    - '#2e3434'
    - '#b7aa97'
    - '#75604b'
  brandStrength: 1
  lightness: 0.125
  saturation: 0.6212314590811729
  rhythmicContrast: 0.8873746027238667
purpose: []
